In [ ]:
# [start:end]

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print (arr[1:5])

[2 3 4 5]


In [2]:
#Slice elements from index 4 to the end of the array:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print (arr[4:])


[5 6 7]


In [3]:
# slice elements from the beginning to idenx 4 (not included)
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]
